const workoutPlan = [
  {
    name: 'shoulder',
    sections: [
      {
        name: 'warmUp',
        exercises: [
          {
            name: 'doggy-scapular',
            sets: 2,
            repetitions: 10,
            repetitionsUnit: 'rep.',
            resistance: '',
            resistanceUnit: '',
          },
          {
            name: 'jesus-push-up',
            sets: 3,
            repetitions: 1,
            repetitionsUnit: 'failure',
            resistance: '',
            resistanceUnit: '',
          },
          {
            name: 'w-on-the-wall',
            sets: 2,
            repetitions: 1,
            repetitionsUnit: 'minute',
            resistance: '',
            resistanceUnit: '',
          },
        ],
      },
      {
        name: 'strength',
        exercises: [
          // {
          //   name: 'external-rotation-single-hand',
          //   sets: 0,
          //   repetitions: 12,
          //   repetitionsUnit: 'rep.',
          //   resistance: 10,
          //   resistanceUnit: 'lbs.',
          // },
          {
            name: 'external-rotation-double-hand',
            sets: 3,
            repetitions: 12,
            repetitionsUnit: 'rep.',
            resistance: 10,
            resistanceUnit: 'lbs.',
          },
          {
            name: 'scapular-depression',
            sets: 4,
            repetitions: 12,
            repetitionsUnit: 'rep.',
            resistance: 60,
            resistanceUnit: 'kg',
          },
          {
            name: 'face-pull',
            sets: 3,
            repetitions: 12,
            repetitionsUnit: 'rep.',
            resistance: 45,
            resistanceUnit: 'kg',
          },
          {
            name: 'inverted-push-ups',
            sets: 3,
            repetitions: 12,
            repetitionsUnit: 'rep.',
            resistance: 1,
            resistanceUnit: 'body weight',
          },
        ],
      },
      {
        name: 'core',
        exercises: [
          {
            name: 'hollow-body',
            sets: 3,
            repetitions: 20,
            repetitionsUnit: 'rep.',
            resistance: '',
            resistanceUnit: '',
          },
          {
            name: 'walkouts',
            sets: 2,
            repetitions: '',
            repetitionsUnit: '',
            resistance: 40,
            resistanceUnit: 'kg',
          },
        ],
      },
      {
        name: 'stretch',
        exercises: [
          {
            name: 'external-rotators',
            sets: 0,
            repetitions: 2,
            repetitionsUnit: 'minutes.',
            resistance: '',
            resistanceUnit: '',
          },
          {
            name: 'delt',
            sets: 0,
            repetitions: 2,
            repetitionsUnit: 'minutes.',
            resistance: '',
            resistanceUnit: '',
          },
          {
            name: 'neck',
            sets: 0,
            repetitions: 30,
            repetitionsUnit: 'seconds.',
            resistance: '',
            resistanceUnit: '',
          },
        ],
      },
    ],
  },
  {
    name: 'push',
    sections: [
      {
        name: 'warmUp',
        exercises: [
          {
            name: 'pezzi-wall',
            sets: 2,
            repetitions: 8,
            repetitionsUnit: 'rep.',
            resistance: '',
            resistanceUnit: '',
          },
          {
            name: 'doggy-scapular',
            sets: 2,
            repetitions: 8,
            repetitionsUnit: 'rep.',
            resistance: '',
            resistanceUnit: '',
          },
          {
            name: 'jesus-push-up',
            sets: 3,
            repetitions: 1,
            repetitionsUnit: 'failure',
            resistance: '',
            resistanceUnit: '',
          },
        ],
      },
      {
        name: 'strength',
        exercises: [
          {
            name: 'incline-press',
            sets: 3,
            repetitions: 12,
            repetitionsUnit: 'rep.',
            resistance: 5,
            resistanceUnit: 'kg',
          },
          {
            name: 'smith-bench-flat',
            sets: 3,
            repetitions: 12,
            repetitionsUnit: 'rep.',
            resistance: 5,
            resistanceUnit: 'kg',
          },
          {
            name: 'low-cable-crossover',
            sets: 3,
            repetitions: 12,
            repetitionsUnit: 'rep.',
            resistance: 10,
            resistanceUnit: 'kg',
          },
          {
            name: 'shoulder-press',
            sets: 3,
            repetitions: 10,
            repetitionsUnit: 'rep.',
            resistance: 6,
            resistanceUnit: 'kg',
          },
          {
            name: 'rear-extensions',
            sets: 3,
            repetitions: 12,
            repetitionsUnit: 'rep.',
            resistance: 4,
            resistanceUnit: 'kg',
          },
          {
            name: 'bench-extensions',
            sets: 3,
            repetitions: 12,
            repetitionsUnit: 'rep.',
            resistance: 4,
            resistanceUnit: 'kg',
          },
        ],
      },
      {
        name: 'core',
        exercises: [
          {
            name: 'arch-hold',
            sets: 3,
            repetitions: 1,
            repetitionsUnit: 'failure',
            resistance: '',
            resistanceUnit: '',
          },
          {
            name: 'trigger-ups',
            sets: 3,
            repetitions: 15,
            repetitionsUnit: 'rep.',
            resistance: 1,
            resistanceUnit: 'body weight',
          },
          {
            name: 'horizontal-rotation',
            sets: 3,
            repetitions: 15,
            repetitionsUnit: 'rep.',
            resistance: 10,
            resistanceUnit: 'kg',
          },
        ],
      },
      {
        name: 'stretch',
        exercises: [
          {
            name: 'pec-minor',
            sets: 0,
            repetitions: 2,
            repetitionsUnit: 'minutes.',
            resistance: '',
            resistanceUnit: '',
          },
          {
            name: 'pec-major',
            sets: 0,
            repetitions: 2,
            repetitionsUnit: 'minutes.',
            resistance: '',
            resistanceUnit: '',
          },
          {
            name: 'triceps',
            sets: 0,
            repetitions: 2,
            repetitionsUnit: 'minutes.',
            resistance: '',
            resistanceUnit: '',
          },
          {
            name: 'front-delt',
            sets: 0,
            repetitions: 2,
            repetitionsUnit: 'minutes.',
            resistance: '',
            resistanceUnit: '',
          },
          {
            name: 'internal-rotators',
            sets: 0,
            repetitions: 2,
            repetitionsUnit: 'minutes.',
            resistance: '',
            resistanceUnit: '',
          },
        ],
      },
    ],
  },
  {
    name: 'pull',
    sections: [
      {
        name: 'warmUp',
        exercises: [
          {
            name: 'doggy-scapular',
            sets: 2,
            repetitions: 10,
            repetitionsUnit: '',
            resistance: '',
            resistanceUnit: '',
          },
          {
            name: 'jesus-push-up',
            sets: 3,
            repetitions: 1,
            repetitionsUnit: 'failure',
            resistance: '',
            resistanceUnit: '',
          },
          {
            name: 'w-on-the-wall',
            sets: 2,
            repetitions: 1,
            repetitionsUnit: 'minute',
            resistance: '',
            resistanceUnit: '',
          },
          {
            name: 'biceps',
            sets: 0,
            repetitions: 2,
            repetitionsUnit: 'minutes.',
            resistance: '',
            resistanceUnit: '',
          },
          {
            name: 'external-rotators',
            sets: 0,
            repetitions: 2,
            repetitionsUnit: 'minutes.',
            resistance: '',
            resistanceUnit: '',
          },
          {
            name: 'rear-delts',
            sets: 0,
            repetitions: 2,
            repetitionsUnit: 'minutes.',
            resistance: '',
            resistanceUnit: '',
          },
        ],
      },
    ],
  },
  {
    name: 'leg',
    sections: [
      {
        name: 'warmUp',
        exercises: [
          {
            name: 'dry-squads',
            sets: 0,
            repetitions: 0,
            repetitionsUnit: 'rep.',
            resistance: 2,
            resistanceUnit: 'kg',
          },
          {
            name: 'hip-tilts',
            sets: 0,
            repetitions: 0,
            repetitionsUnit: 'rep.',
            resistance: 2,
            resistanceUnit: 'kg',
          },
        ],
      },
      {
        name: 'strength',
        exercises: [
          {
            name: 'lunges',
            sets: 0,
            repetitions: 0,
            repetitionsUnit: 'rep.',
            resistance: 2,
            resistanceUnit: 'kg',
          },
          {
            name: 'lunges-rear-leg-lifted',
            sets: 0,
            repetitions: 0,
            repetitionsUnit: 'rep.',
            resistance: 2,
            resistanceUnit: 'kg',
          },
          {
            name: 'calve-raises',
            sets: 0,
            repetitions: 0,
            repetitionsUnit: 'rep.',
            resistance: 2,
            resistanceUnit: 'kg',
          },
          {
            name: 'leg-press',
            sets: 0,
            repetitions: 0,
            repetitionsUnit: 'rep.',
            resistance: 2,
            resistanceUnit: 'kg',
          },
          {
            name: 'deep-squad-hold',
            sets: 0,
            repetitions: 0,
            repetitionsUnit: 'rep.',
            resistance: 2,
            resistanceUnit: 'kg',
          },
          {
            name: 'bad-girls',
            sets: 0,
            repetitions: 0,
            repetitionsUnit: 'rep.',
            resistance: 2,
            resistanceUnit: 'kg',
          },
          {
            name: 'glute-bridges',
            sets: 0,
            repetitions: 0,
            repetitionsUnit: 'rep.',
            resistance: 2,
            resistanceUnit: 'kg',
          },
        ],
      },
      {
        name: 'core',
        exercises: [
          {
            name: 'hanging-hip-hinge',
            sets: 0,
            repetitions: 0,
            repetitionsUnit: 'rep.',
            resistance: 2,
            resistanceUnit: 'kg',
          },
        ],
      },
      {
        name: 'stretch',
        exercises: [
          {
            name: 'calves-and-glutes',
            sets: 0,
            repetitions: 2,
            repetitionsUnit: 'minutes.',
            resistance: '',
            resistanceUnit: '',
          },
          {
            name: 'quads-and-back-leg',
            sets: 0,
            repetitions: 2,
            repetitionsUnit: 'minutes.',
            resistance: '',
            resistanceUnit: '',
          },
        ],
      },
    ],
  },
];

export default workoutPlan;
